package com.glaitozen.tableorganizer.discord;

public enum TableCommands {
    CREER_TABLE, AJOUTER_LISTE_PROPOSITION_DATE, CONFIRMER_DATE, LISTER_TABLES, DETAILS_TABLE, EFFACER_TABLE, MAJ_TABLE,
    AJOUTER_JOUEUR, SUPPRIMER_JOUEUR, AJOUTER_RAPPEL, EFFACER_RAPPEL, AFFICHER_PROCHAINE_DATE, AFFICHER_PROPOSITIONS_DATE,
    RELANCER_JOUEURS
}
